apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ghcr-pull.sops.yaml
  - namespace.yaml
  - photos.yaml
  - postgres.yaml
  - backup-cronjob.yaml
  - recovery-postgres.yaml
  - recovery-refresh-cronjob.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
