apiVersion: v1
kind: ResourceQuota
metadata:
  name: wdmv-test
  namespace: wdmv-test
spec:
  hard:
    requests.cpu: "1500m"
    requests.memory: 3Gi
    limits.memory: 6Gi
    persistentvolumeclaims: "2"
    requests.storage: 8Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: wdmv-test
  namespace: wdmv-test
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 128Mi
      default:
        memory: 1Gi
